### PR TITLE
Added Quality Presets for Video Downloads and Custom Download Location

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
### Overview:
This PR enhances the YouTube downloader script with new features:

1. **Custom Download Location:** Allows users to specify where downloaded files will be saved.
2. **Video Quality Presets:** Users can select from predefined video quality settings.

These improvements provide greater flexibility and control over download options.

### Key Changes:
1. **Custom Download Location:**
- Added a prompt for users to specify the path where the downloaded files will be saved.
Video Quality Presets:

2. **Added options for video quality:**

- 1: Worst quality
- 2: 480p resolution
- 3: 720p resolution
- 4: Best quality

3. **Updated User Prompts:**
- Improved user interaction with clear instructions for quality and location choices.

### Testing:
- The updated script has been tested with various YouTube URLs, download options, and quality presets to ensure functionality and robustness.

By incorporating these changes, the script is now more user-friendly and versatile, catering to a wider range of user needs and preferences.

Please review the changes and merge if everything looks good!

### CODE REVIEW

**Review by Vadkon07 — COMMENTED** [review]
10/10, good work! About progress indicator in to-do I'm not sure, because this app already has it. I will check it again, maybe your code removed this output from yt dlp

**Comment by Vadkon07** [comment]
[download] Destination: /home/user/Coding_Projects/Coding_Projects_Python/YouTube_Downloader/[FREE] YN JAY x DETROIT TYPE BEAT - ＂ALPHA＂.webm

[download] 100% of    2.29MiB in 00:00:02 at 973.11KiB/s

[ExtractAudio] Destination: /home/user/Coding_Projects/Coding_Projects_Python/YouTube_Downloader/[FREE] YN JAY x DETROIT TYPE BEAT - ＂ALPHA＂.mp3

### So it already has it, we can remove it from To-Do

**Comment by mgiannopoulos24** [comment]
Yeah we could make a better indicator though. Also you had a small text saying that you used this software for your studio or something. Please add it on README.

**Comment by Vadkon07** [comment]
I added it in the beginning, because consumer should start to think that this product is really useful for him as earlier as it's possible :)

**Pull request merged**
